language: python

python:
  - "3.5"

install:
  - pip install .[test]

jobs:
  include:
    - stage: lint
      script: flake8 ./srem/*.py
    - stage: type check
      script: mypy ./srem/*.py
    - stage: unit test
      script: pytest tests
