language: python
python:
- '3.5'
install:
- pip install .[test]
jobs:
  include:
  - stage: lint
    script: flake8 ./srem/*.py
  - stage: type check
    script: mypy ./srem/*.py
  - stage: unit test
    script: pytest tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: WrkBSX/fo8j1/VbeKR19clKVdUR0UEAnYFVj91qO5PYF94D8vP4o1soXH7WrdIFpNFq7cIvUokTmDnRvjRG3vumwCzXI3+59hyH5r6t/78AXjzwqf7wU+fj2+s+eXOnRW0mz1IN52844AIeRIh9A6SuJoVU1Kx/O9Aria6CepA35LfqbGBDHl6XtGRRPhT28jDG1Z1k/wU9wcXFDSqZhE7wtGBoPF9NYhhV7qjz0Mx9BWg+e3ODhShXLVXJv2N2meDSQgxLzdd+vRj4yY1UgqN8yf/MsRtPwLqlgz+7PPi31ziyf5Bi+6FEe8yt9m4tExBZfI8owWzNJ/gIv1EweJpvhcnZ53bEkXtQrMgYIb/+dooMlCoLHP2n5mboE05KzKqJ+S1tVSJ6bNg8SVW5t/3PR/cf8LpcQUEBRGH2OEr0goDJBcinwwdDyGRhjwgWnNAqB53VDv92s6IJd4mJJ4UoN+u/SU1mP1Qb7X4iE0XeTDSHYCtdGXDA8MMGrUNW+Nfkpc21xp6Fx/Rt7nAbCl777uHmRacYSrq6JquQ1cQ5pGABlzotEdP6zy/qJjXBqKQMGwyy8toMou61NJxnAaZOrXWmRvy9xus5tVxKf5GcLz1Ef+OCgSk9/fd7DYPJU295wegAd5zWHV04P3qKxsBF41TNM9k/1iDHLx+4aCTM=
  on:
    tags: true
