language: python
python:
- '3.5'
install:
- pip install .[test]
jobs:
  include:
  - stage: lint
    script: flake8 ./srem/*.py
  - stage: type check
    script: mypy ./srem/*.py
  - stage: unit test
    script: pytest tests
deploy:
  provider: pypi
  user: oyam
  password:
    secure: qxnZSmv+Ta94FZ46McIof9h+ADH+eYjDk5bumqvEItVdE0HOJHSuIsv4F8RQrtgmBg9j9OECAFe4rXu4jPHJDD1H85aDk6L6hzjOkOpuczm7WlhKnIsClXW0KjCg9J7p4hYLgdfbRLC4QZ+U7uNrfvXZh3tTp1bRLNn6UuEO/9QIGgWEBrN4zCdpwPTJhvWboFP5KAWvKj+ftiTxw4gPCjpSTnIo0Z05LA//z5polG/it9OyEyWQqua9HATjFAv2vNISHw3qnMAYXyhFPLrlLzLoQWKGCJArvnL/1VubfU/G1WZWeTr9PSsk69FM8Gbj8tCCLMcLQN6Aw4P3MCCFEO+6QnWYaXuoqnXM0W2F/3RBOnnxf1yQAccRqTz/58EYQ31l2Is9Ox+704nG5iNji7qOXVq29eNhNTJLQC/W4JcODySfGv2mEJeFVHMcuhkB65AQ2GVaMUDpzOLNMqHSZ8Lqmm/nPgW3IN1Wh6UZ4gNEC2EmsgjcVGJbOLsXZifVp1Svw2Aaufa/M3XUNYifDESWYl4pdwfX0EyOrR5YYm5Vmq8VgOrVnnEv3rmFxNznMTbr2qmDxWNP/WZogrPfV2nuzuxfmWhan23JdsRQSiaVnV/TRU/C9Kyj5SlVD/VWLJfpTft9RVUeM3du+6ZB8KJ1wuR13HfWtqziWXclYe4=
  on:
    tags: true
