language: python
python:
- '3.5'
install:
- pip install .[test]
jobs:
  include:
  - stage: lint
    script: flake8 ./srem/*.py
  - stage: type check
    script: mypy ./srem/*.py
  - stage: unit test
    script: pytest tests
deploy:
  provider: pypi
  user: oyam
  password:
    secure: LB1CYoygMmtvmU99kz37cVBgD0cl6NukVRLQPDyEhvoYtLRvFUfZ5Toh1W4IDhuFcj+9BavzlSBCB8nNUvwjzSf9ykNegZxdEFrJscYNx2VjygkdFklRu4UfFRDnwc0kWxD9JW7m+WSCAqI9PB6lCvn80PeZWa07KLju2je5Zkn5INMFGnRO/wMB89hrMRUkh8zYmS1SQreWB00npFAEziYeCJGkGArQurhVW4424QgOaAhVkyyZZ6DcuN50eLnmd91neImL1/Lc421pet8f2CRns3PMuE34lc2rrjgSCDJYhF/i7erctdYgfFhtSWLrWunGjxcSEPBBYdF+sqsQTQtzmfJJrPG2pBfp8XjDAg1hM5iyBgx4VkeM0+ZsxSjZ4uTR0ZWTx9i6MVrd2VM/gryTc3Wb84PFzeAz+IG+JHnXiW9y1xnHU2Ed+wRTzwjJ6rkKv97vu4huPE2iOn2p1FhF9jWbgOjTRVoj2H814W5Vp1JECT4iW9Z095pfUkmgX/0/WzXtnlS4DiCzAy6oMNsNSjmRtSoCjg7rB4ZolSUbJTPVkhG6FQ1B6t/2v/fZJbUoK2mKYMYmNidrc/siuKsgTEEKFFa4HeiU5D1YoJJQXcbXgwjl063k+0oVv1dGOowWUuxVxpbYRC6L5chMeD82E4p3ySOuUAig9j6HEXk=
  on:
    tags: true
