language: python
python:
- '3.5'
install:
- pip install .[test]
jobs:
  include:
  - stage: lint
    script: flake8 ./srem/*.py
  - stage: type check
    script: mypy ./srem/*.py
  - stage: unit test
    script: pytest tests
deploy:
  provider: pypi
  user: oyam
  password:
    secure: igwfGBRiuSadWjKS0ctulhkm/n3gier/sS7EnAAfUiuC1aCkkLij3+z46+KRnwWwVITWYY4OC2GcCGgAXNV9iBekH+ZZ/LBHEmlQ1q+MqT25HWkmf8WJGZ/3sx7/hSn3v2gYX1jJ5wLdoRmC/AzDhqEy2Q8z04jsvClVaRlUYtPKSFzmkC1YxuuTK/k8UfmKnnXhweVMDuHgWPLcwDg8nnbyolRATf/YCJBMRRz5CANFAn7EdkaeITPgBH8GyaN322X5w7cJ4hg8oMp9/Nmv00+E5agPJFq4S7xmWLMSbTlTW5yfMzAXrkYolr1qG6AzvdV9+n1KxU6YFLzTPc6Er6JpIYf9Mzm5UG4QayuLav7roMnSnvuwK/a/HMsqS5zx8igFbhAMrLAHFeYywHnEr3BSmDqGQAh1s8hIgnFokLNgkxlNOh2hl47QOYFsrk4dgDNlScvixFhl4K+K8Ka1aPagPJVqY7PEFganiXsffXqs1ACpGbpQwVmYjRudUQ9Q8pxCg2e2YcXgjPBFAEAIyfKzPzmy1dEE/AQCdcd21nUTxsve9tAi7caqv5jJIPD9ntlOIb8Dj1iTI2ACrqTmAl4fi2ldYUIqt640e3Fe9oIlynp3m8QmSVNfSt27zlFbxrqPeejB+tCUrJIEpZJfHFY5Jmu3Z9LdyMKYqjO0bDI=
  on:
    tags: true
