language: python
python:
- '3.5'
install:
- pip install .[test]
jobs:
  include:
  - stage: lint
    script: flake8 ./srem/*.py
  - stage: type check
    script: mypy ./srem/*.py
  - stage: unit test
    script: pytest tests
deploy:
  provider: pypi
  user: oyam
  password:
    secure: JcsWYy4BBNEyxCe0eQKAVexDC3O3ooezB+yIN4ACeDFdCyFjEWX2yCw/GTUf+huZkd5ZYDovLfWLZ1wE7nnstXaPAnQN22GbDaBSSL8pRSOwL/3cv9vnNPPSLcaa1+aCedAYPjRkV8jKenpoeoyR4wdNuWMR1jfioGcEUyYF4gjcHZ4iHAIil+zCm7aWlVzFuzztUzqUneU3ILb9SvY4BxxowKIy8R1iv66Yi/yzQNMYrYe3krZRqBZzl18Yzvj9DODsDjFK744hWn2No0ddgQWJsaG7hhC5n8Ouom+ZIaanGc5xXJ6eAAlkmVDCjnERN47e5RqYdMOO1DFabGEDUdyxXvkFe3cUaP4eQL62iahpfQjQwNowYmKg4tDLeT/XnA32BzEKoHpteYXRXJ9Ea7Emg9qCSKtTmhecEgdoO1xCKsTreqRT11sLpGrOi34ZbdI2fGIY4MN0PfTIiiF66gvAfL2HuEGSuBQ99p81YpqNVinjjERPQieJRq/UTNqftOn0Yj22bcUxX8Kf4He94urjLOeowR/7TnsxqHUNvy9woSslHzrzy5h8KNH2lPx7Ef4bGvnGZB8J6+sW3Imxn4aftFY/57cYdUpceqFHPWwmAwCR9U6qN+F8lMR4m4f/970d6B+5oktCwhm1aJEqhL5ms/9IoxRG/oXPJdw14nU=
  edge: true
  on:
    tags: true
